[global]
# Completely disable all telemetry and analytics
showWarningOnDirectExecution = false

[browser]
# Browser configuration
serverAddress = "localhost"
gatherUsageStats = false

[server]
# Server configuration  
headless = false
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
maxUploadSize = 200

[client]
# Client settings
showErrorDetails = false

[theme]
# UI theme to prevent additional requests
base = "light"